import { fireEvent, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { describe, expect, it } from 'vitest'
import { ApiError, type ApiClient } from '../api/client'
import { createClubState, createEmptyState } from '../api/mock/fixtures'
import { createMockClient, type MockOptions } from '../api/mock/mockClient'
import { holdCalls, trackCalls } from '../test/clients'
import { renderApp } from '../test/renderApp'

// Small generated byte arrays, never a real photo.
const image = (type: string, size = 16, name = 'foto') => new File([new Uint8Array(size).fill(7)], name, { type })
const png = () => image('image/png', 16, 'cuadrado.png')
const SAVED_PHOTO = 'data:image/png;base64,iVBORw0KGgo='
// Set by the in-flight test's client wrapper.
let held: ReturnType<typeof holdCalls> | undefined

async function openForm(options: MockOptions = {}, wrap: (client: ApiClient) => ApiClient = (c) => c) {
  const tracked = trackCalls(createMockClient(options))
  const rendered = renderApp({ path: '/mi-perfil', client: wrap(tracked.client) })
  await screen.findByLabelText('Nombre visible')
  return { ...rendered, tracked, saves: () => tracked.calls.filter((m) => m === 'updateMyProfile').length }
}

const nameInput = () => screen.getByLabelText('Nombre visible') as HTMLInputElement
const bioInput = () => screen.getByLabelText('Sobre mí') as HTMLTextAreaElement
const quoteInput = () => screen.getByLabelText('Cita favorita') as HTMLTextAreaElement
const fileInput = () => screen.getByLabelText('Elegir una foto') as HTMLInputElement
const addSelect = () => screen.getByLabelText('Añadir un libro favorito') as HTMLSelectElement
const saveButton = () => screen.getByRole('button', { name: /Guardar cambios|Guardando…/ })
const favourites = () => screen.getByRole('group', { name: 'Libros favoritos' })
const chosenTitles = () =>
  within(favourites())
    .queryAllByRole('listitem')
    .map((item) => item.querySelector('span')!.textContent)
const describedBy = (element: HTMLElement) =>
  (element.getAttribute('aria-describedby') ?? '')
    .split(' ')
    .map((id) => document.getElementById(id)?.textContent)

// Rejects updateMyProfile with the given status; every other call goes to the mock.
function refusingSave(status: number) {
  return (client: ApiClient): ApiClient =>
    new Proxy(client, {
      get(target, property, receiver) {
        if (property === 'updateMyProfile') return () => Promise.reject(new ApiError(status, 'Rechazado.'))
        return Reflect.get(target, property, receiver)
      },
    })
}

describe('Profile form: initial values', () => {
  it('starts with the default admin’s saved values, limits and hints', async () => {
    await openForm()
    expect(nameInput()).toHaveValue('Lucía')
    expect(nameInput()).toBeRequired()
    expect(nameInput()).toHaveAttribute('maxLength', '40')
    expect(describedBy(nameInput())).toEqual(['Entre 1 y 40 caracteres. Es el nombre que verá el club.'])
    expect(bioInput()).toHaveValue('Organizo las reuniones y siempre llevo demasiados marcapáginas.')
    expect(bioInput()).toHaveAttribute('maxLength', '500')
    expect(describedBy(bioInput())).toEqual(['Opcional. Hasta 500 caracteres.'])
    expect(quoteInput()).toHaveValue('Leer es viajar sin moverse de la silla.')
    expect(quoteInput()).toHaveAttribute('maxLength', '300')
    expect(describedBy(quoteInput())).toEqual(['Opcional. Hasta 300 caracteres.'])
    expect(fileInput()).toHaveAttribute('accept', 'image/jpeg,image/png,image/webp')
    expect(describedBy(fileInput())).toEqual(['JPEG, PNG o WebP, hasta 2 MB.'])
    expect(chosenTitles()).toEqual(['1. Niebla', '2. Cumbres borrascosas'])
    expect([...addSelect().options].map((o) => o.text)).toEqual([
      'Ángel Guerra',
      'El ingenioso hidalgo don Quijote de la Mancha',
      'El sí de las niñas',
      'Fortunata y Jacinta',
    ])
    expect(within(favourites()).getByText('Hasta 5 libros que el club haya leído, en el orden que prefieras.')).toBeInTheDocument()
    // No photo yet: the initials are decorative, and there is nothing to remove.
    expect(screen.queryByRole('img', { name: /Foto de/ })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Quitar foto' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Mantener la foto actual' })).not.toBeInTheDocument()
    expect(screen.getByRole('main').textContent).not.toMatch(/Discord/)
  })

  it('starts with the default member’s values: no bio, a quote and one favourite', async () => {
    await openForm({ session: 'member' })
    expect(nameInput()).toHaveValue('Mateo')
    expect(bioInput()).toHaveValue('')
    expect(quoteInput()).toHaveValue('Un libro abierto es un cerebro que habla.')
    expect(chosenTitles()).toEqual(['1. El ingenioso hidalgo don Quijote de la Mancha'])
  })

  it('shows a saved photo at a large size with its alt text', async () => {
    const state = createClubState()
    state.members[0].avatarUrl = SAVED_PHOTO
    await openForm({ state })
    const photo = screen.getByRole('img', { name: 'Foto de Lucía' })
    expect(photo).toHaveAttribute('src', SAVED_PHOTO)
    expect(photo).toHaveStyle({ width: '96px', height: '96px' })
    expect(screen.getByRole('button', { name: 'Quitar foto' })).toBeInTheDocument()
  })
})

describe('Profile form: validation on «Guardar cambios»', () => {
  it('refuses a blank name with no call, marks it, moves focus to it and clears the error when edited', async () => {
    const user = userEvent.setup()
    const { saves } = await openForm()
    await user.clear(nameInput())
    await user.type(nameInput(), '   ')
    await user.click(saveButton())

    expect(nameInput()).toHaveFocus()
    expect(nameInput()).toHaveAttribute('aria-invalid', 'true')
    expect(describedBy(nameInput())).toContain('Escribe un nombre.')
    expect(saves()).toBe(0)

    await user.type(nameInput(), 'Zoe')
    expect(nameInput()).not.toHaveAttribute('aria-invalid')
    expect(screen.queryByText('Escribe un nombre.')).not.toBeInTheDocument()
  })

  it('refuses every field over its limit, focusing the first invalid one', async () => {
    const user = userEvent.setup()
    const { saves } = await openForm()
    // Past the maxLength attribute, as a paste in an old browser could be.
    fireEvent.change(bioInput(), { target: { value: 'b'.repeat(501) } })
    fireEvent.change(quoteInput(), { target: { value: 'c'.repeat(301) } })
    await user.click(saveButton())

    expect(bioInput()).toHaveFocus()
    expect(describedBy(bioInput())).toContain('Este texto puede tener como máximo 500 caracteres.')
    expect(describedBy(quoteInput())).toContain('La cita puede tener como máximo 300 caracteres.')
    expect(bioInput()).toHaveAttribute('aria-invalid', 'true')
    expect(quoteInput()).toHaveAttribute('aria-invalid', 'true')
    expect(nameInput()).not.toHaveAttribute('aria-invalid')
    expect(saves()).toBe(0)

    fireEvent.change(nameInput(), { target: { value: 'n'.repeat(41) } })
    await user.click(saveButton())
    expect(nameInput()).toHaveFocus()
    expect(describedBy(nameInput())).toContain('El nombre puede tener como máximo 40 caracteres.')

    await user.clear(bioInput())
    expect(bioInput()).not.toHaveAttribute('aria-invalid')
    expect(quoteInput()).toHaveAttribute('aria-invalid', 'true')
    expect(saves()).toBe(0)
  })

  it('refuses a name with a control character', async () => {
    const user = userEvent.setup()
    const { saves } = await openForm()
    fireEvent.change(nameInput(), { target: { value: 'Lu\tcía' } })
    await user.click(saveButton())
    expect(describedBy(nameInput())).toContain('Escribe el nombre en una sola línea.')
    expect(saves()).toBe(0)
  })
})

describe('Profile form: avatar', () => {
  it('previews a valid image without sending anything', async () => {
    const user = userEvent.setup()
    const { saves, tracked } = await openForm()
    await user.upload(fileInput(), png())

    const preview = await screen.findByRole('img', { name: 'Vista previa de tu nueva foto' })
    expect(preview.getAttribute('src')).toMatch(/^data:image\/png;base64,/)
    expect(screen.getByText('La nueva foto se guardará al pulsar «Guardar cambios».')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Mantener la foto actual' })).toBeInTheDocument()
    expect(saves()).toBe(0)
    expect(tracked.clubDataCalls().sort()).toEqual(['getMyProfile', 'listMyReviews'])
  })

  it.each([
    ['a GIF', image('image/gif', 40, 'anim.gif'), 'La foto debe ser JPEG, PNG o WebP.'],
    ['an SVG', image('image/svg+xml', 40, 'dibujo.svg'), 'La foto debe ser JPEG, PNG o WebP.'],
    ['an empty file', image('image/png', 0, 'vacia.png'), 'Ese archivo está vacío. Elige otra foto.'],
    ['a file over 2 MB', image('image/jpeg', 2_097_153, 'grande.jpg'), 'La foto puede ocupar como máximo 2 MB.'],
  ])('refuses %s, keeping the previous preview and making no call', async (_case, file, message) => {
    // The refused file must reach the handler, not be filtered by `accept`.
    const user = userEvent.setup({ applyAccept: false })
    const { saves } = await openForm()
    await user.upload(fileInput(), png())
    const preview = await screen.findByRole('img', { name: 'Vista previa de tu nueva foto' })
    const src = preview.getAttribute('src')

    await user.upload(fileInput(), file)
    expect(await screen.findByText(message)).toBeInTheDocument()
    expect(fileInput()).toHaveAttribute('aria-invalid', 'true')
    expect(describedBy(fileInput())).toEqual(['JPEG, PNG o WebP, hasta 2 MB.', message])
    expect(screen.getByRole('img', { name: 'Vista previa de tu nueva foto' })).toHaveAttribute('src', src)
    expect(saves()).toBe(0)

    // A valid choice clears the error.
    await user.upload(fileInput(), image('image/webp', 8, 'otra.webp'))
    await waitFor(() => expect(screen.queryByText(message)).not.toBeInTheDocument())
    expect(fileInput()).not.toHaveAttribute('aria-invalid')
  })

  it('refuses a GIF with no previous preview: the initials stay', async () => {
    const user = userEvent.setup({ applyAccept: false })
    await openForm()
    await user.upload(fileInput(), image('image/gif', 40, 'anim.gif'))
    expect(await screen.findByText('La foto debe ser JPEG, PNG o WebP.')).toBeInTheDocument()
    expect(screen.queryByRole('img', { name: /Vista previa|Foto de/ })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Mantener la foto actual' })).not.toBeInTheDocument()
  })

  it('sets a pending removal with «Quitar foto» and restores the saved photo with «Mantener la foto actual»', async () => {
    const user = userEvent.setup()
    const state = createClubState()
    state.members[0].avatarUrl = SAVED_PHOTO
    const { saves } = await openForm({ state })

    await user.click(screen.getByRole('button', { name: 'Quitar foto' }))
    expect(screen.queryByRole('img', { name: 'Foto de Lucía' })).not.toBeInTheDocument()
    expect(screen.getByText('Tu foto se quitará al pulsar «Guardar cambios».')).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Quitar foto' })).not.toBeInTheDocument()
    const keep = screen.getByRole('button', { name: 'Mantener la foto actual' })
    expect(keep).toHaveFocus()

    await user.click(keep)
    expect(screen.getByRole('img', { name: 'Foto de Lucía' })).toHaveAttribute('src', SAVED_PHOTO)
    expect(screen.queryByText(/se quitará/)).not.toBeInTheDocument()
    expect(fileInput()).toHaveFocus()
    expect(saves()).toBe(0)
  })

  it('drops a pending image with «Mantener la foto actual», and removes one with «Quitar foto»', async () => {
    const user = userEvent.setup()
    await openForm()
    await user.upload(fileInput(), png())
    await screen.findByRole('img', { name: 'Vista previa de tu nueva foto' })
    await user.click(screen.getByRole('button', { name: 'Mantener la foto actual' }))
    expect(screen.queryByRole('img', { name: 'Vista previa de tu nueva foto' })).not.toBeInTheDocument()

    await user.upload(fileInput(), png())
    await screen.findByRole('img', { name: 'Vista previa de tu nueva foto' })
    await user.click(screen.getByRole('button', { name: 'Quitar foto' }))
    expect(screen.queryByRole('img', { name: 'Vista previa de tu nueva foto' })).not.toBeInTheDocument()
    expect(screen.getByText('Tu foto se quitará al pulsar «Guardar cambios».')).toBeInTheDocument()
  })
})

describe('Profile form: favourite books', () => {
  it('adds a book at the end and announces it', async () => {
    const user = userEvent.setup()
    await openForm()
    await user.selectOptions(addSelect(), 'Fortunata y Jacinta')
    await user.click(screen.getByRole('button', { name: 'Añadir' }))
    expect(chosenTitles()).toEqual(['1. Niebla', '2. Cumbres borrascosas', '3. Fortunata y Jacinta'])
    expect(within(favourites()).getByRole('status')).toHaveTextContent('Se ha añadido «Fortunata y Jacinta»: posición 3 de 3.')
    expect([...addSelect().options].map((o) => o.text)).not.toContain('Fortunata y Jacinta')
  })

  it('reorders with «Subir» and «Bajar», keeping focus on the moved book', async () => {
    const user = userEvent.setup()
    await openForm()
    const up = screen.getByRole('button', { name: 'Subir «Niebla»' })
    expect(up).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Bajar «Cumbres borrascosas»' })).toBeDisabled()

    await user.click(screen.getByRole('button', { name: 'Bajar «Niebla»' }))
    expect(chosenTitles()).toEqual(['1. Cumbres borrascosas', '2. Niebla'])
    // «Bajar» is now disabled for the last book, so focus goes to its «Subir».
    expect(screen.getByRole('button', { name: 'Subir «Niebla»' })).toHaveFocus()
    expect(within(favourites()).getByRole('status')).toHaveTextContent('Niebla: posición 2 de 2.')

    await user.selectOptions(addSelect(), 'Ángel Guerra')
    await user.click(screen.getByRole('button', { name: 'Añadir' }))
    await user.click(screen.getByRole('button', { name: 'Subir «Ángel Guerra»' }))
    expect(chosenTitles()).toEqual(['1. Cumbres borrascosas', '2. Ángel Guerra', '3. Niebla'])
    // Still usable, so focus stays on the same button.
    expect(screen.getByRole('button', { name: 'Subir «Ángel Guerra»' })).toHaveFocus()
    await user.keyboard('{Enter}')
    expect(chosenTitles()).toEqual(['1. Ángel Guerra', '2. Cumbres borrascosas', '3. Niebla'])
    expect(screen.getByRole('button', { name: 'Bajar «Ángel Guerra»' })).toHaveFocus()
    expect(within(favourites()).getByRole('status')).toHaveTextContent('Ángel Guerra: posición 1 de 3.')
  })

  it('moves focus after a removal to the next «Quitar», the previous one, then the add control', async () => {
    const user = userEvent.setup()
    await openForm()
    await user.selectOptions(addSelect(), 'Ángel Guerra')
    await user.click(screen.getByRole('button', { name: 'Añadir' }))

    await user.click(screen.getByRole('button', { name: 'Quitar «Niebla»' }))
    expect(chosenTitles()).toEqual(['1. Cumbres borrascosas', '2. Ángel Guerra'])
    expect(screen.getByRole('button', { name: 'Quitar «Cumbres borrascosas»' })).toHaveFocus()
    expect(within(favourites()).getByRole('status')).toHaveTextContent('Se ha quitado «Niebla» de tus libros favoritos.')

    await user.click(screen.getByRole('button', { name: 'Quitar «Ángel Guerra»' }))
    expect(screen.getByRole('button', { name: 'Quitar «Cumbres borrascosas»' })).toHaveFocus()

    await user.keyboard('{Enter}')
    expect(chosenTitles()).toEqual([])
    expect(within(favourites()).getByText('Aún no hay libros favoritos.')).toBeInTheDocument()
    expect(addSelect()).toHaveFocus()
  })

  it('allows at most 5: the add controls are disabled with a note', async () => {
    const user = userEvent.setup()
    await openForm()
    for (const title of ['Ángel Guerra', 'El sí de las niñas', 'Fortunata y Jacinta']) {
      await user.selectOptions(addSelect(), title)
      await user.click(screen.getByRole('button', { name: 'Añadir' }))
    }
    expect(chosenTitles()).toHaveLength(5)
    expect(addSelect()).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Añadir' })).toBeDisabled()
    expect(screen.getByText('Ya tienes 5 libros favoritos, que es el máximo. Quita uno si quieres añadir otro.')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Quitar «Fortunata y Jacinta»' })).toHaveFocus()

    await user.click(screen.getByRole('button', { name: 'Quitar «Niebla»' }))
    expect(addSelect()).toBeEnabled()
    expect(screen.queryByText(/que es el máximo/)).not.toBeInTheDocument()
  })

  it('shows a calm empty list when there are no favourites', async () => {
    const state = createClubState()
    state.profiles.m1.favouriteBookIds = []
    await openForm({ state })
    expect(within(favourites()).getByText('Aún no hay libros favoritos.')).toBeInTheDocument()
    expect(within(favourites()).queryByRole('list')).not.toBeInTheDocument()
    expect(addSelect().options).toHaveLength(6)
  })

  it('has no select in a club that has not finished any book', async () => {
    await openForm({ state: createEmptyState() })
    expect(within(favourites()).getByText('Aún no hay libros favoritos.')).toBeInTheDocument()
    expect(
      within(favourites()).getByText('El club aún no ha terminado ningún libro. Cuando lo haga, podrás elegir aquí tus favoritos.'),
    ).toBeInTheDocument()
    expect(screen.queryByLabelText('Añadir un libro favorito')).not.toBeInTheDocument()
    expect(within(favourites()).queryByRole('button')).not.toBeInTheDocument()
  })

  it('shows books only as titles and authors: no score, status or date', async () => {
    await openForm()
    expect(favourites().textContent).not.toMatch(/\d[,.]\d|Terminado|Archivado|terminado|archivado|\d{4}|estrella|media/i)
  })
})

describe('Profile form: saving', () => {
  it('saves everything at once, shows «Guardando…» in flight, then the trimmed values and a status', async () => {
    const user = userEvent.setup()
    const state = createClubState()
    const { saves } = await openForm({ state }, (client) => {
      held = holdCalls(client, 'updateMyProfile')
      return held.client
    })
    await user.clear(nameInput())
    await user.type(nameInput(), '  Zoe  ')
    await user.clear(bioInput())
    await user.type(bioInput(), '  Primera línea.{Enter}Segunda línea.  ')
    await user.clear(quoteInput())
    await user.type(quoteInput(), '   ')
    await user.click(screen.getByRole('button', { name: 'Bajar «Niebla»' }))
    await user.upload(fileInput(), png())
    await screen.findByRole('img', { name: 'Vista previa de tu nueva foto' })
    await user.click(saveButton())

    expect(saveButton()).toHaveTextContent('Guardando…')
    expect(saveButton()).toBeDisabled()
    // A second click while in flight sends nothing more.
    await user.click(saveButton())
    held!.release()

    expect(await screen.findByText('Tu perfil se ha guardado.')).toHaveAttribute('role', 'status')
    expect(saveButton()).toHaveTextContent('Guardar cambios')
    expect(saveButton()).toBeEnabled()
    expect(saves()).toBe(1)
    expect(nameInput()).toHaveValue('Zoe')
    expect(bioInput()).toHaveValue('Primera línea.\nSegunda línea.')
    expect(quoteInput()).toHaveValue('')
    expect(chosenTitles()).toEqual(['1. Cumbres borrascosas', '2. Niebla'])
    // The pending photo is now the saved one.
    expect(screen.queryByRole('img', { name: 'Vista previa de tu nueva foto' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Mantener la foto actual' })).not.toBeInTheDocument()
    const photo = screen.getByRole('img', { name: 'Foto de Zoe' })
    expect(photo.getAttribute('src')).toMatch(/^data:image\/png;base64,/)

    expect(state.members[0]).toMatchObject({ displayName: 'Zoe', avatarUrl: photo.getAttribute('src') })
    expect(state.profiles.m1).toEqual({
      bio: 'Primera línea.\nSegunda línea.',
      favouriteQuote: null,
      favouriteBookIds: ['b2', 'b1'],
    })
  })

  it('saves a pending removal of the photo', async () => {
    const user = userEvent.setup()
    const state = createClubState()
    state.members[0].avatarUrl = SAVED_PHOTO
    await openForm({ state })
    await user.click(screen.getByRole('button', { name: 'Quitar foto' }))
    await user.click(saveButton())
    expect(await screen.findByText('Tu perfil se ha guardado.')).toBeInTheDocument()
    expect(state.members[0].avatarUrl).toBeNull()
    expect(screen.queryByRole('img', { name: 'Foto de Lucía' })).not.toBeInTheDocument()
    expect(screen.queryByText(/se quitará/)).not.toBeInTheDocument()
  })

  it('keeps every entered value after a failure, with an alert, and saves on a second try', async () => {
    const user = userEvent.setup()
    const state = createClubState()
    const { saves } = await openForm({ state, failures: { updateMyProfile: 1 } })
    await user.clear(nameInput())
    await user.type(nameInput(), 'Zoe')
    await user.click(screen.getByRole('button', { name: 'Bajar «Niebla»' }))
    await user.upload(fileInput(), png())
    const src = (await screen.findByRole('img', { name: 'Vista previa de tu nueva foto' })).getAttribute('src')
    await user.click(saveButton())

    expect(await screen.findByRole('alert')).toHaveTextContent('No se ha podido guardar tu perfil. Inténtalo de nuevo.')
    expect(nameInput()).toHaveValue('Zoe')
    expect(chosenTitles()).toEqual(['1. Cumbres borrascosas', '2. Niebla'])
    expect(screen.getByRole('img', { name: 'Vista previa de tu nueva foto' })).toHaveAttribute('src', src)
    expect(saveButton()).toBeEnabled()
    expect(state.members[0].displayName).toBe('Lucía')

    await user.click(saveButton())
    expect(await screen.findByText('Tu perfil se ha guardado.')).toBeInTheDocument()
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    expect(saves()).toBe(2)
    expect(state.members[0].displayName).toBe('Zoe')
  })

  it('says some data is not valid after a 400, keeping the values', async () => {
    const user = userEvent.setup()
    const state = createClubState()
    await openForm({ state })
    await user.clear(nameInput())
    await user.type(nameInput(), 'Zoe')
    // The server no longer accepts «Niebla» as a favourite.
    state.books.find((b) => b.id === 'b1')!.status = 'leyendo'
    await user.click(saveButton())
    expect(await screen.findByRole('alert')).toHaveTextContent('Algunos datos no son válidos. Revísalos y vuelve a intentarlo.')
    expect(nameInput()).toHaveValue('Zoe')
    expect(chosenTitles()).toEqual(['1. Niebla', '2. Cumbres borrascosas'])
    expect(state.members[0].displayName).toBe('Lucía')
  })

  it('says the profile could not be saved after a 403', async () => {
    const user = userEvent.setup()
    await openForm({}, refusingSave(403))
    await user.click(saveButton())
    expect(await screen.findByRole('alert')).toHaveTextContent('No se ha podido guardar tu perfil. Inténtalo de nuevo.')
    expect(saveButton()).toBeEnabled()
  })

  it('goes to the sign-in screen after a 401', async () => {
    const user = userEvent.setup()
    const state = createClubState()
    await openForm({ state })
    state.session = 'anonymous'
    await user.click(saveButton())
    expect(await screen.findByRole('button', { name: 'Entrar con Discord' })).toBeInTheDocument()
    expect(screen.queryByLabelText('Nombre visible')).not.toBeInTheDocument()
  })
})

