import { describe, expect, it } from 'vitest'
import { ApiError, type ApiClient } from '../client'
import type { CriterionScores, ProfileUpdate } from '../types'
import { withUnauthorizedHandler } from '../unauthorized'
import { createClubState, createEmptyState, type MockState } from './fixtures'
import { createMockClient, type MockOptions } from './mockClient'

const keys = (value: object) => Object.keys(value).sort()
const titles = (books: { title: string }[]) => books.map((b) => b.title)
const flat = (score: number): CriterionScores => ({ disfrute: score, estilo: score, personajes: score, trama: score, huella: score })
const snapshot = (state: MockState) => JSON.parse(JSON.stringify(state)) as unknown

async function rejection(promise: Promise<unknown>): Promise<ApiError> {
  try {
    await promise
  } catch (error) {
    return error as ApiError
  }
  throw new Error('expected the call to reject')
}

// Small generated byte arrays, never a real photo.
const image = (type: string, size = 16, name = 'foto') => new File([new Uint8Array(size).fill(7)], name, { type })
const PNG = () => image('image/png', 16, 'cuadrado.png')

// Lucía's saved profile, unchanged.
const KEEP_ADMIN: ProfileUpdate = {
  displayName: 'Lucía',
  bio: 'Organizo las reuniones y siempre llevo demasiados marcapáginas.',
  favouriteQuote: 'Leer es viajar sin moverse de la silla.',
  favouriteBookIds: ['b1', 'b2'],
  avatar: { action: 'keep' },
}
const update = (changes: Partial<ProfileUpdate> = {}): ProfileUpdate => ({ ...KEEP_ADMIN, ...changes })

const OPTIONS = [
  'Ángel Guerra',
  'Cumbres borrascosas',
  'El ingenioso hidalgo don Quijote de la Mancha',
  'El sí de las niñas',
  'Fortunata y Jacinta',
  'Niebla',
]

describe('getMyProfile', () => {
  it('gives the default admin her saved profile and every read book as an option, by title', async () => {
    const profile = await createMockClient().getMyProfile()
    expect(keys(profile)).toEqual(['bio', 'favouriteBooks', 'favouriteOptions', 'favouriteQuote', 'member'])
    expect(profile.member).toEqual({ id: 'm1', displayName: 'Lucía', avatarUrl: null })
    expect(profile.bio).toBe(KEEP_ADMIN.bio)
    expect(profile.favouriteQuote).toBe(KEEP_ADMIN.favouriteQuote)
    expect(titles(profile.favouriteBooks)).toEqual(['Niebla', 'Cumbres borrascosas'])
    expect(titles(profile.favouriteOptions)).toEqual(OPTIONS)
    for (const book of [...profile.favouriteBooks, ...profile.favouriteOptions]) {
      expect(keys(book)).toEqual(['authors', 'coverUrl', 'id', 'title'])
    }
  })

  it('gives the default member his own profile', async () => {
    const profile = await createMockClient({ session: 'member' }).getMyProfile()
    expect(profile.member).toEqual({ id: 'm2', displayName: 'Mateo', avatarUrl: null })
    expect(profile.bio).toBeNull()
    expect(profile.favouriteQuote).toBe('Un libro abierto es un cerebro que habla.')
    expect(titles(profile.favouriteBooks)).toEqual(['El ingenioso hidalgo don Quijote de la Mancha'])
    expect(titles(profile.favouriteOptions)).toEqual(OPTIONS)
  })

  it('gives an empty profile and no options in the empty club', async () => {
    expect(await createMockClient({ state: createEmptyState() }).getMyProfile()).toEqual({
      member: { id: 'm1', displayName: 'Lucía', avatarUrl: null },
      bio: null,
      favouriteQuote: null,
      favouriteBooks: [],
      favouriteOptions: [],
    })
  })
})

describe('Mi perfil calls when not signed in', () => {
  const calls: [string, (api: ApiClient) => Promise<unknown>][] = [
    ['getMyProfile', (api) => api.getMyProfile()],
    ['updateMyProfile', (api) => api.updateMyProfile(update())],
    ['listMyReviews', (api) => api.listMyReviews()],
  ]

  it.each(calls.flatMap(([name, call]) => (['anonymous', 'denied'] as const).map((s) => [name, s, call] as const)))(
    '%s rejects with 401 while the session is %s, even with a failure configured',
    async (name, session, call) => {
      const state = createClubState()
      const api = createMockClient({ state, session, failures: { [name]: 1 } })
      const before = snapshot(state)
      expect((await rejection(call(api))).status).toBe(401)
      expect(snapshot(state)).toEqual(before)
    },
  )

  it.each(calls)('%s goes through the 401 handler', async (_name, call) => {
    let unauthorized = 0
    const api = withUnauthorizedHandler(createMockClient({ session: 'anonymous' }), () => unauthorized++)
    await rejection(call(api))
    expect(unauthorized).toBe(1)
  })

  it.each(calls)('%s fails once with the failures option, then succeeds', async (name, call) => {
    const api = createMockClient({ failures: { [name]: 1 } })
    expect((await rejection(call(api))).status).toBe(500)
    await expect(call(api)).resolves.toBeDefined()
  })
})

describe('updateMyProfile: refused calls', () => {
  it('fails with the simulated failure before the 403, and changes nothing', async () => {
    const state = createClubState()
    const before = snapshot(state)
    const api = createMockClient({ state, failures: { updateMyProfile: 1 } })
    const input = { ...update({ displayName: 'Otra' }), memberId: 'm3' }
    expect((await rejection(api.updateMyProfile(input))).status).toBe(500)
    expect(snapshot(state)).toEqual(before)
  })

  it.each((['member', 'admin'] as const).flatMap((session) => ['id', 'memberId', 'userId'].map((key) => [session, key] as const)))(
    'refuses the %s with 403 for another member’s id in «%s», before the 400, changing nothing',
    async (session, key) => {
      const state = createClubState()
      const api = createMockClient({ state, session })
      const before = snapshot(state)
      // Bypasses the types, as an attacker could with the HTTP API.
      const input = { ...update({ displayName: 'Nombre robado' }), [key]: 'm3' } as ProfileUpdate
      expect((await rejection(api.updateMyProfile(input))).status).toBe(403)
      // 403 comes before 400: an invalid input with another id is still a 403.
      const invalid = { ...update({ displayName: '' }), [key]: 'm4' } as ProfileUpdate
      expect((await rejection(api.updateMyProfile(invalid))).status).toBe(403)
      expect(snapshot(state)).toEqual(before)
    },
  )

  it('accepts an input that carries the signed-in user’s own id', async () => {
    const api = createMockClient({ session: 'member' })
    const input = { ...update({ displayName: 'Mateo', favouriteBookIds: [] }), memberId: 'm2' } as ProfileUpdate
    expect((await api.updateMyProfile(input)).member.displayName).toBe('Mateo')
  })

  const invalidInputs: [string, Partial<ProfileUpdate>][] = [
    ['an empty name', { displayName: '' }],
    ['a blank name', { displayName: '   ' }],
    ['a name of 41 characters', { displayName: 'a'.repeat(41) }],
    ['a name with a line break', { displayName: 'Lucía\nGarcía' }],
    ['a name with a tab', { displayName: 'Lucía\tGarcía' }],
    ['a bio of 501 characters', { bio: 'b'.repeat(501) }],
    ['a quote of 301 characters', { favouriteQuote: 'c'.repeat(301) }],
    ['six favourites', { favouriteBookIds: ['b1', 'b2', 'b6', 'b12', 'b13', 'b14'] }],
    ['a duplicate favourite', { favouriteBookIds: ['b1', 'b1'] }],
    ['an unknown favourite', { favouriteBookIds: ['no-existe'] }],
    ['a favourite that is being read', { favouriteBookIds: ['b3'] }],
    ['a favourite that is chosen', { favouriteBookIds: ['b4'] }],
    ['a favourite that is proposed', { favouriteBookIds: ['b5'] }],
    ['an SVG avatar', { avatar: { action: 'replace', file: image('image/svg+xml', 40, 'dibujo.svg') } }],
    ['a GIF avatar', { avatar: { action: 'replace', file: image('image/gif', 40, 'anim.gif') } }],
    ['a text file as avatar', { avatar: { action: 'replace', file: image('text/plain', 40, 'nota.txt') } }],
    ['an empty avatar file', { avatar: { action: 'replace', file: image('image/png', 0) } }],
    ['an avatar of 2 MB plus one byte', { avatar: { action: 'replace', file: image('image/jpeg', 2_097_153) } }],
  ]

  it.each(invalidInputs)('refuses %s with 400 and changes nothing, the avatar included', async (_case, changes) => {
    const state = createClubState()
    state.members[0].avatarUrl = 'data:image/png;base64,AAAA'
    const before = snapshot(state)
    const api = createMockClient({ state })
    // Valid changes elsewhere in the same input must not be saved either.
    const input = update({ displayName: 'Lucía Nueva', bio: 'Nueva', favouriteBookIds: ['b6'], avatar: { action: 'remove' }, ...changes })
    expect((await rejection(api.updateMyProfile(input))).status).toBe(400)
    expect(snapshot(state)).toEqual(before)
  })
})

describe('updateMyProfile: saving', () => {
  it('stores trimmed values, blank texts as null, keeps line breaks and returns the new profile', async () => {
    const state = createClubState()
    const api = createMockClient({ state })
    const saved = await api.updateMyProfile({
      displayName: '  Lucía G.  ',
      bio: '  Primera línea.\nSegunda línea.  ',
      favouriteQuote: '   ',
      favouriteBookIds: ['b14', 'b6', 'b1'],
      avatar: { action: 'keep' },
    })
    expect(saved).toEqual(await api.getMyProfile())
    expect(saved.member).toEqual({ id: 'm1', displayName: 'Lucía G.', avatarUrl: null })
    expect(saved.bio).toBe('Primera línea.\nSegunda línea.')
    expect(saved.favouriteQuote).toBeNull()
    expect(titles(saved.favouriteBooks)).toEqual(['El ingenioso hidalgo don Quijote de la Mancha', 'Ángel Guerra', 'Niebla'])
  })

  it('accepts a name of 40 characters, a bio of 500 and a quote of 300, and no favourites', async () => {
    const api = createMockClient()
    const saved = await api.updateMyProfile(
      update({ displayName: 'n'.repeat(40), bio: 'b'.repeat(500), favouriteQuote: 'c'.repeat(300), favouriteBookIds: [] }),
    )
    expect([saved.member.displayName.length, saved.bio!.length, saved.favouriteQuote!.length]).toEqual([40, 500, 300])
    expect(saved.favouriteBooks).toEqual([])
  })

  it('accepts five favourites, archived and finished', async () => {
    const saved = await createMockClient().updateMyProfile(update({ favouriteBookIds: ['b13', 'b12', 'b6', 'b2', 'b1'] }))
    expect(saved.favouriteBooks.map((b) => b.id)).toEqual(['b13', 'b12', 'b6', 'b2', 'b1'])
  })

  it.each(['image/jpeg', 'image/png', 'image/webp'])('keeps a %s avatar in memory as a data URL', async (type) => {
    const saved = await createMockClient().updateMyProfile(update({ avatar: { action: 'replace', file: image(type) } }))
    expect(saved.member.avatarUrl).toMatch(new RegExp(`^data:${type.replace('/', '\\/')};base64,`))
  })

  it('accepts an avatar of exactly 2 MB (2 097 152 bytes)', async () => {
    const saved = await createMockClient().updateMyProfile(update({ avatar: { action: 'replace', file: image('image/png', 2_097_152) } }))
    expect(saved.member.avatarUrl).toMatch(/^data:image\/png;base64,/)
  })

  it('keeps the avatar with «keep» and removes it with «remove»', async () => {
    const state = createClubState()
    const api = createMockClient({ state })
    const withPhoto = await api.updateMyProfile(update({ avatar: { action: 'replace', file: PNG() } }))
    const kept = await api.updateMyProfile(update({ avatar: { action: 'keep' } }))
    expect(kept.member.avatarUrl).toBe(withPhoto.member.avatarUrl)
    const removed = await api.updateMyProfile(update({ avatar: { action: 'remove' } }))
    expect(removed.member.avatarUrl).toBeNull()
    expect(state.members[0].avatarUrl).toBeNull()
  })

  it('changes nothing for the other members, the revoked member or the role', async () => {
    const state = createClubState()
    const before = snapshot(state) as MockState
    await createMockClient({ state, session: 'member' }).updateMyProfile({
      displayName: 'Mateo R.',
      bio: 'Nuevo',
      favouriteQuote: null,
      favouriteBookIds: [],
      avatar: { action: 'replace', file: PNG() },
    })
    expect(state.members.filter((m) => m.id !== 'm2')).toEqual(before.members.filter((m) => m.id !== 'm2'))
    expect(state.members.find((m) => m.id === 'm2')!.role).toBe('member')
    expect(state.revokedMembers).toEqual(before.revokedMembers)
    const { m2: _mine, ...others } = state.profiles
    const { m2: _before, ...othersBefore } = before.profiles
    expect(others).toEqual(othersBefore)
    expect(state.currentUserId).toBe('m2')
  })

  it('lets two members share a display name', async () => {
    const saved = await createMockClient({ session: 'member' }).updateMyProfile({
      displayName: 'Lucía',
      bio: null,
      favouriteQuote: null,
      favouriteBookIds: [],
      avatar: { action: 'keep' },
    })
    expect(saved.member).toEqual({ id: 'm2', displayName: 'Lucía', avatarUrl: null })
  })
})

describe('The new name and avatar show in every call that returns the member', () => {
  it('renames the default admin and gives her an avatar, without recreating the client', async () => {
    const api = createMockClient()
    const saved = await api.updateMyProfile(update({ displayName: 'Zoe', avatar: { action: 'replace', file: PNG() } }))
    const me = { id: 'm1', displayName: 'Zoe', avatarUrl: saved.member.avatarUrl }
    expect(me.avatarUrl).toMatch(/^data:image\/png;base64,/)

    const session = await api.getSession()
    expect(session).toEqual({ status: 'signedIn', user: { ...me, role: 'admin' } })

    const directory = await api.listMembers()
    expect(directory.members.map((e) => e.member.displayName)).toEqual(['Carmen', 'Elena', 'Inés', 'Jordi', 'Mateo', 'Pablo', 'Zoe'])
    expect(directory.members.at(-1)).toEqual({ member: me, isMe: true, completedCurrentWeek: false })

    expect((await api.getMemberProfile('m1')).member).toEqual(me)
    expect((await api.getHome()).memberProgress.find((p) => p.member.id === 'm1')!.member).toEqual(me)

    const ratings = await api.getBookRatings('b2')
    expect(ratings.club.status === 'visible' && ratings.club.reviews.find((r) => r.isMine)!.member).toEqual(me)

    const votes = await api.getVotes()
    expect(votes.current!.candidates.find((c) => c.book.id === 'b5')!.approvals).toContainEqual(me)
    expect((await api.getVote('v0')).candidates.find((c) => c.book.id === 'b2')!.approvals).toContainEqual(me)

    expect((await api.getMeeting('mt1')).attendance).toContainEqual(me)

    const statistics = await api.getStatistics()
    expect(statistics.ratings.status === 'available' && statistics.ratings.members.find((m) => m.isMe)!.member).toEqual(me)

    // The old name is gone from every one of them.
    const everything = JSON.stringify([
      session,
      directory,
      await api.getHome(),
      ratings,
      votes,
      await api.getVote('v0'),
      await api.getMeeting('mt1'),
      statistics,
    ])
    expect(everything).not.toContain('Lucía')
  })

  it('shows the default member’s new name to the admin in the same state', async () => {
    const state = createClubState()
    await createMockClient({ state, session: 'member' }).updateMyProfile({
      displayName: 'Mateo Rivas',
      bio: null,
      favouriteQuote: null,
      favouriteBookIds: [],
      avatar: { action: 'keep' },
    })
    const admin = createMockClient({ state, session: 'admin' })
    expect((await admin.getMemberProfile('m2')).member.displayName).toBe('Mateo Rivas')
    expect((await admin.getVote('v2')).candidates.find((c) => c.book.id === 'b9')!.approvals[0].displayName).toBe('Mateo Rivas')
  })
})

describe('listMyReviews', () => {
  it('lists the default admin’s four reviews, newest activity first', async () => {
    const reviews = await createMockClient().listMyReviews()
    expect(titles(reviews.map((r) => r.book))).toEqual([
      'El ingenioso hidalgo don Quijote de la Mancha',
      'El sí de las niñas',
      'Fortunata y Jacinta',
      'Cumbres borrascosas',
    ])
    expect(reviews[3]).toEqual({
      book: { id: 'b2', title: 'Cumbres borrascosas', authors: ['Emily Brontë'], coverUrl: null },
      scores: { disfrute: 5, estilo: 4.5, personajes: 3, trama: 4, huella: 2.5 },
      overall: 3.8,
      text: 'Me atrapó desde el principio, aunque el final se me hizo largo.',
      submittedAt: '2024-12-02T21:10:00+01:00',
      editedAt: null,
    })
    for (const review of reviews) {
      expect(keys(review)).toEqual(['book', 'editedAt', 'overall', 'scores', 'submittedAt', 'text'])
      expect(keys(review.book)).toEqual(['authors', 'coverUrl', 'id', 'title'])
    }
  })

  it('lists the default member’s two reviews', async () => {
    const reviews = await createMockClient({ session: 'member' }).listMyReviews()
    expect(titles(reviews.map((r) => r.book))).toEqual(['El ingenioso hidalgo don Quijote de la Mancha', 'Niebla'])
  })

  it('is empty in the empty club', async () => {
    expect(await createMockClient({ state: createEmptyState() }).listMyReviews()).toEqual([])
  })

  it('puts an edited review first, by its edit date', async () => {
    const api = createMockClient()
    await api.saveMyReview('b2', { scores: flat(4), text: 'Cambié de opinión.' })
    const reviews = await api.listMyReviews()
    expect(reviews[0]).toMatchObject({ book: { id: 'b2' }, overall: 4, text: 'Cambié de opinión.', editedAt: '2026-10-09T12:00:00+02:00' })
    expect(reviews[0].submittedAt).toBe('2024-12-02T21:10:00+01:00')
    expect(reviews).toHaveLength(4)
  })

  it('puts a new review first', async () => {
    const api = createMockClient()
    await api.setBookFinished('b6', true)
    await api.saveMyReview('b6', { scores: flat(3), text: null })
    const reviews = await api.listMyReviews()
    expect(titles(reviews.map((r) => r.book))).toEqual([
      'Ángel Guerra',
      'El ingenioso hidalgo don Quijote de la Mancha',
      'El sí de las niñas',
      'Fortunata y Jacinta',
      'Cumbres borrascosas',
    ])
  })

  it('orders reviews with the same latest date by title', async () => {
    const api = createMockClient()
    await api.setBookFinished('b6', true)
    await api.saveMyReview('b6', { scores: flat(3), text: null })
    await api.saveMyReview('b2', { scores: flat(3), text: null })
    expect(titles((await api.listMyReviews()).slice(0, 2).map((r) => r.book))).toEqual(['Ángel Guerra', 'Cumbres borrascosas'])
  })

  it('never contains another member’s id, name or review text, nor any club data', async () => {
    const state = createClubState()
    const json = JSON.stringify(await createMockClient({ state }).listMyReviews())
    for (const member of [...state.members, ...state.revokedMembers].filter((m) => m.id !== 'm1')) {
      expect(json).not.toContain(`"${member.id}"`)
      expect(json).not.toContain(member.displayName)
    }
    for (const review of state.reviews.filter((r) => r.userId !== 'm1' && r.text)) {
      expect(json).not.toContain(JSON.stringify(review.text).slice(1, -1))
    }
    expect(json).not.toMatch(/"(club|reviewCount|overallMean|criterionMeans|isMine|member|n)"/)
  })
})

describe('Role parity', () => {
  it.each([
    ['getMyProfile', (api: ApiClient) => api.getMyProfile()],
    ['listMyReviews', (api: ApiClient) => api.listMyReviews()],
  ] as const)('%s gives the same viewer an identical result as admin and as member', async (_name, call) => {
    const state = createClubState()
    const asAdmin = await call(createMockClient({ state }))
    state.members.find((m) => m.id === 'm1')!.role = 'member'
    const asMember = await call(createMockClient({ state }))
    expect(asMember).toEqual(asAdmin)
  })

  it('gives the default member the same kind of result as the admin, with no other key', async () => {
    const options: MockOptions = { session: 'member' }
    const profile = await createMockClient(options).getMyProfile()
    expect(keys(profile)).toEqual(['bio', 'favouriteBooks', 'favouriteOptions', 'favouriteQuote', 'member'])
    expect(keys(profile.member)).toEqual(['avatarUrl', 'displayName', 'id'])
  })
})
