import { fireEvent, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { describe, expect, it } from 'vitest'
import { ApiError, type ApiClient } from '../api/client'
import { createClubState, createEmptyState } from '../api/mock/fixtures'
import { createMockClient, type MockOptions } from '../api/mock/mockClient'
import { holdCalls, trackCalls } from '../test/clients'
import { renderApp } from '../test/renderApp'

const PATH = '/administracion/libros'
async function form(options: MockOptions & { client?: ApiClient; edit?: string } = {}) {
  const state = options.state ?? createClubState()
  const tracked = trackCalls(options.client ?? createMockClient({ ...options, state }))
  const app = renderApp({ path: options.edit ? `${PATH}/${options.edit}/editar` : `${PATH}/nuevo`, client: tracked.client })
  await screen.findByRole('textbox', { name: 'Título' })
  return { ...app, state, tracked }
}
const field = (name: string) => screen.getByRole('textbox', { name })
const save = () => screen.getByRole('button', { name: 'Guardar libro' })
const value = (name: string, text: string) => fireEvent.change(field(name), { target: { value: text } })
async function findMetadata() {
  const user = userEvent.setup()
  value('Título o autor', 'jardín')
  await user.click(screen.getByRole('button', { name: 'Buscar metadatos' }))
  return await screen.findByRole('button', { name: 'Usar metadatos de «El jardín de las cartas»' })
}

describe('admin catalogue navigation and loading', () => {
  it('links from the hub to the entire catalogue, create and edit', async () => {
    const user = userEvent.setup()
    renderApp({ path: '/administracion' })
    await user.click(await screen.findByRole('link', { name: 'Libros' }))
    expect(await screen.findByRole('heading', { name: 'Catálogo' })).toBeInTheDocument()
    expect(screen.getByRole('link', { name: 'Añadir libro' })).toHaveAttribute('href', `${PATH}/nuevo`)
    expect(screen.getAllByRole('link', { name: /^Editar «/ })).toHaveLength(createClubState().books.length)
    await user.click(screen.getByRole('link', { name: 'Editar «La Regenta»' }))
    expect(await screen.findByRole('textbox', { name: 'Título' })).toHaveValue('La Regenta')
  })
  it('shows loading, retryable list error, then empty state', async () => {
    const user = userEvent.setup()
    const held = holdCalls(createMockClient({ state: createEmptyState(), failures: { listAdminBooks: 1 } }), 'listAdminBooks')
    const tracked = trackCalls(held.client)
    renderApp({ path: PATH, client: tracked.client })
    await waitFor(() => expect(tracked.calls).toContain('listAdminBooks'))
    expect(screen.getByText('Cargando…')).toBeInTheDocument()
    held.release()
    expect(await screen.findByText('No se ha podido cargar el catálogo.')).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Reintentar' }))
    expect(await screen.findByText(/Aún no hay libros en el catálogo/)).toBeInTheDocument()
  })
  it('retries edit load failures and shows not-found for unknown ids', async () => {
    const user = userEvent.setup()
    renderApp({ path: `${PATH}/unknown/editar`, client: createMockClient({ failures: { getAdminBook: 1 } }) })
    expect(await screen.findByText('No se ha podido cargar este libro.')).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Reintentar' }))
    expect(await screen.findByRole('heading', { name: 'No encontramos este libro' })).toBeInTheDocument()
  })
  it.each(['member', 'curator'] as const)('guards all catalogue routes for %s without admin calls', async (session) => {
    for (const path of [PATH, `${PATH}/nuevo`, `${PATH}/b3/editar`]) {
      const tracked = trackCalls(createMockClient({ session }))
      const rendered = renderApp({ path, client: tracked.client })
      expect(await screen.findByRole('heading', { name: 'Sección reservada' })).toBeInTheDocument()
      expect(tracked.clubDataCalls()).toEqual([])
      rendered.unmount()
    }
  })
})

describe('metadata selection and manual fallback', () => {
  it('refuses blank query without a call, fills only blank editable fields and never saves or changes dates/status', async () => {
    const user = userEvent.setup(), { tracked } = await form()
    await user.click(screen.getByRole('button', { name: 'Buscar metadatos' }))
    expect(screen.getByRole('alert')).toHaveTextContent('Escribe un título o autor')
    expect(tracked.calls).not.toContain('searchBookMetadata')
    value('Título', 'Corrección manual'); value('Editorial', 'Mi editorial'); value('Inicio real', '2026-01-01')
    await user.selectOptions(screen.getByRole('combobox', { name: 'Estado' }), 'terminado')
    await user.click(await findMetadata())
    expect(field('Título')).toHaveValue('Corrección manual')
    expect(field('Editorial')).toHaveValue('Mi editorial')
    expect(field('Autores (uno por línea)')).toHaveValue('Alba del Río\nNicolás Prado')
    expect(field('Número de páginas')).toHaveValue('240')
    expect(field('Inicio real')).toHaveValue('2026-01-01')
    expect(screen.getByRole('combobox', { name: 'Estado' })).toHaveValue('terminado')
    expect(screen.getByRole('img', { name: /Portada de/ })).toHaveAttribute('src', expect.stringMatching(/^data:image\/png/))
    value('Descripción', 'Corregida a mano')
    expect(field('Descripción')).toHaveValue('Corregida a mano')
    expect(tracked.calls).not.toContain('createBook')
  })
  it('leaves manual entry usable after search failure and empty results', async () => {
    const user = userEvent.setup()
    await form({ failures: { searchBookMetadata: 1 } })
    value('Título o autor', 'jardín')
    await user.click(screen.getByRole('button', { name: 'Buscar metadatos' }))
    expect(await screen.findByText(/No se han podido buscar metadatos/)).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Añadir a mano' }))
    expect(field('Título')).toHaveFocus()
    value('Título o autor', 'missing')
    await user.click(screen.getByRole('button', { name: 'Buscar metadatos' }))
    expect(await screen.findByText(/No encontramos metadatos/)).toBeInTheDocument()
    value('Título', 'Manual')
    await user.click(save())
    expect(await screen.findByRole('heading', { level: 1, name: 'Manual' })).toBeInTheDocument()
  })
})

describe('atomic cover and field saves', () => {
  it('reports labelled errors and focuses invalid fields without calling the API', async () => {
    const user = userEvent.setup(), { tracked } = await form()
    await user.click(save())
    expect(field('Título')).toHaveAttribute('aria-invalid', 'true')
    expect(field('Título')).toHaveAccessibleDescription('Escribe un título.')
    expect(field('Título')).toHaveFocus()
    value('Título', 'Válido'); value('Número de páginas', '2.5'); value('Inicio real', '2026-02-30')
    value('Inicio previsto', '2026-10-10'); value('Fin previsto', '2026-10-09')
    await user.click(save())
    expect(field('Número de páginas')).toHaveAccessibleDescription('Escribe un número entero positivo de páginas.')
    expect(field('Inicio real')).toHaveAccessibleDescription('Escribe una fecha válida (AAAA-MM-DD).')
    expect(field('Fin previsto')).toHaveAccessibleDescription('La fecha final no puede ser anterior a la inicial.')
    expect(tracked.calls).not.toContain('createBook')
  })
  it('keeps entered values and prior saved cover on failure, then retries the whole change', async () => {
    const user = userEvent.setup(), { state } = await form({ edit: 'b3', failures: { updateBook: 1 } })
    const old = JSON.stringify(state.books.find((b) => b.id === 'b3'))
    value('Título', 'Nuevo título')
    const file = new File(['cover'], 'x.png', { type: 'image/png' })
    await user.upload(screen.getByLabelText('Subir o reemplazar portada'), file)
    await waitFor(() => expect(screen.getByRole('img', { name: 'Portada de «Nuevo título»' })).toHaveAttribute('src', expect.stringMatching(/^data:image\/png/)))
    expect(JSON.stringify(state.books.find((b) => b.id === 'b3'))).toBe(old)
    await user.click(save())
    expect(await screen.findByText(/No se ha podido guardar el libro/)).toBeInTheDocument()
    expect(field('Título')).toHaveValue('Nuevo título')
    expect(JSON.stringify(state.books.find((b) => b.id === 'b3'))).toBe(old)
    await user.click(screen.getByRole('button', { name: 'Reintentar guardar' }))
    expect(await screen.findByRole('heading', { level: 1, name: 'Nuevo título' })).toBeInTheDocument()
    expect(state.books.find((b) => b.id === 'b3')?.coverUrl).toMatch(/^data:image\/png/)
  })
  it('preserves uploaded/removed cover on metadata selection and allows restoring saved cover', async () => {
    const user = userEvent.setup()
    await form()
    const select = await findMetadata()
    await user.upload(screen.getByLabelText('Subir o reemplazar portada'), new File(['uploaded'], 'x.webp', { type: 'image/webp' }))
    await waitFor(() => expect(screen.getByRole('img', { name: /Portada de/ })).toHaveAttribute('src', expect.stringMatching(/^data:image\/webp/)))
    await user.click(select)
    expect(screen.getByRole('img', { name: /Portada de/ })).toHaveAttribute('src', expect.stringMatching(/^data:image\/webp/))
    await user.click(screen.getByRole('button', { name: 'Quitar portada' }))
    await user.click(select)
    expect(screen.getByRole('img', { name: /Portada de/ })).not.toHaveAttribute('src')
    await user.click(save())
    expect(await screen.findByRole('heading', { level: 1, name: 'El jardín de las cartas' })).toBeInTheDocument()
  })
  it('blocks save after an invalid cover until corrected or discarded', async () => {
    const user = userEvent.setup(), { tracked } = await form()
    value('Título', 'Válido')
    fireEvent.change(screen.getByLabelText('Subir o reemplazar portada'), { target: { files: [new File(['x'], 'x.svg', { type: 'image/svg+xml' })] } })
    expect(screen.getByRole('alert')).toHaveTextContent('La portada debe ser JPEG, PNG o WebP.')
    await user.click(save())
    expect(tracked.calls).not.toContain('createBook')
    await user.click(screen.getByRole('button', { name: 'Conservar portada guardada' }))
    await user.click(save())
    expect(await screen.findByRole('heading', { level: 1, name: 'Válido' })).toBeInTheDocument()
  })
  it('disables duplicate submissions while pending', async () => {
    const held = holdCalls(createMockClient(), 'createBook'), tracked = trackCalls(held.client)
    await form({ client: tracked.client })
    value('Título', 'Una sola vez')
    const element = save().closest('form')!
    fireEvent.submit(element); fireEvent.submit(element)
    expect(screen.getByRole('button', { name: 'Guardando…' })).toBeDisabled()
    expect(field('Título')).toBeDisabled()
    expect(tracked.calls.filter((c) => c === 'createBook')).toHaveLength(1)
    held.release()
    expect(await screen.findByRole('heading', { level: 1, name: 'Una sola vez' })).toBeInTheDocument()
  })
  it('names the active book in a conflict and retains the draft', async () => {
    const user = userEvent.setup(), { state } = await form()
    value('Título', 'Segundo activo')
    await user.selectOptions(screen.getByRole('combobox', { name: 'Estado' }), 'leyendo')
    await user.click(save())
    expect(await screen.findByRole('alert')).toHaveTextContent('La Regenta')
    expect(screen.getByRole('alert')).toHaveTextContent('Cambia primero su estado')
    expect(field('Título')).toHaveValue('Segundo activo')
    expect(state.books.some((b) => b.title === 'Segundo activo')).toBe(false)
  })
  it('shows the central reserved message on save 403', async () => {
    const base = createMockClient(), client: ApiClient = { ...base, createBook: async () => { throw new ApiError(403, 'Denied') } }
    const user = userEvent.setup()
    await form({ client }); value('Título', 'Válido'); await user.click(save())
    expect(await screen.findByRole('heading', { name: 'Sección reservada' })).toHaveFocus()
  })
  it('navigates after edit and refreshes Biblioteca and Inicio in the same app', async () => {
    const user = userEvent.setup(), { router, state } = await form({ edit: 'b3' })
    expect(screen.getByText(/Votación de origen \(solo lectura\)/)).toBeInTheDocument()
    value('Título', 'Catálogo corregido'); value('Inicio previsto', '2026-09-01')
    await user.click(save())
    expect(await screen.findByRole('heading', { level: 1, name: 'Catálogo corregido' })).toBeInTheDocument()
    expect(router.state.location.pathname).toBe('/biblioteca/b3')
    expect(screen.getByText('Inicio previsto')).toBeInTheDocument()
    await user.click(within(screen.getByRole('navigation')).getByRole('link', { name: 'Biblioteca' }))
    expect(await screen.findByRole('link', { name: /Catálogo corregido/ })).toBeInTheDocument()
    await user.click(within(screen.getByRole('navigation')).getByRole('link', { name: 'Inicio' }))
    expect(await screen.findByRole('heading', { name: 'Catálogo corregido' })).toBeInTheDocument()
    expect(state.books.find((b) => b.id === 'b3')?.originVote?.id).toBe('v1')
  })
})
