import { fireEvent, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { describe, expect, it } from 'vitest'
import { createClubState } from '../api/mock/fixtures'
import { createMockClient } from '../api/mock/mockClient'
import { holdCalls, trackCalls } from '../test/clients'
import { renderApp } from '../test/renderApp'

const base = '/administracion/lecturas'
const change = (name: string, value: string) => fireEvent.change(screen.getByLabelText(name), { target: { value } })
describe('admin manual reading editor', () => {
  it('links the hub, loads choices and separates retry, empty and unknown states', async () => {
    const user = userEvent.setup()
    const app = renderApp({ path: '/administracion' })
    await user.click(await screen.findByRole('link', { name: 'Planes de lectura' }))
    await user.selectOptions(await screen.findByLabelText('Libro'), 'b4')
    expect(await screen.findByText(/aún no tiene un plan/)).toBeInTheDocument()
    app.unmount()
    const held = holdCalls(createMockClient({ failures: { getAdminReadingPlan: 1 } }), 'getAdminReadingPlan'), tracked = trackCalls(held.client)
    const retryApp = renderApp({ path: `${base}/b3`, client: tracked.client })
    await waitFor(() => expect(tracked.calls).toContain('getAdminReadingPlan'))
    expect(screen.getByText('Cargando…')).toBeInTheDocument(); held.release()
    await screen.findByText('No se han podido cargar los planes de lectura.')
    await user.click(screen.getByRole('button', { name: 'Reintentar' }))
    expect(await screen.findByRole('button', { name: 'Editar semana 1' })).toBeInTheDocument()
    retryApp.unmount()
    renderApp({ path: `${base}/unknown` })
    expect(await screen.findByRole('heading', { name: 'No encontramos este libro' })).toBeInTheDocument()
  })
  it.each(['member', 'curator'] as const)('guards direct paths for %s without reads', async (session) => {
    const tracked = trackCalls(createMockClient({ session }))
    renderApp({ path: `${base}/b3`, client: tracked.client })
    await screen.findByRole('heading', { name: 'Sección reservada' }); expect(tracked.clubDataCalls()).toEqual([])
  })
  it('refuses invalid input, resets acknowledgement and retains drafts/confirmed list on failed writes', async () => {
    const user = userEvent.setup(), state = createClubState(), tracked = trackCalls(createMockClient({ state, failures: { createReadingWeek: 1 } }))
    renderApp({ path: `${base}/b4`, client: tracked.client })
    await user.click(await screen.findByRole('button', { name: 'Añadir semana' }))
    expect(screen.getByLabelText('Porcentaje inicial')).toHaveFocus()
    await user.click(screen.getByRole('button', { name: 'Guardar semana' }))
    expect(screen.getByRole('alert')).toHaveTextContent('porcentajes válidos')
    expect(tracked.calls).not.toContain('createReadingWeek')
    change('Porcentaje inicial', '0'); change('Porcentaje final', '130'); change('Página inicial', '1'); change('Página final', '20')
    await user.click(screen.getByRole('checkbox'))
    change('Porcentaje final', '131'); expect(screen.getByRole('checkbox')).not.toBeChecked()
    await user.click(screen.getByRole('button', { name: 'Guardar semana' })); expect(tracked.calls).not.toContain('createReadingWeek')
    await user.click(screen.getByRole('checkbox')); await user.click(screen.getByRole('button', { name: 'Guardar semana' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('Error simulado')
    expect(screen.getByLabelText('Porcentaje final')).toHaveValue(131); expect(screen.getByText(/aún no tiene un plan/)).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Guardar semana' }))
    expect(await screen.findByText('0–131 % · páginas 1–20')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Añadir semana' })).toHaveFocus()
  })
  it('disables duplicate writes, acknowledges reorder and confirms retained removal with counts', async () => {
    const state = createClubState(), user = userEvent.setup(), held = holdCalls(createMockClient({ state }), 'reorderReadingWeeks')
    state.completions.w1 = ['m1', 'm8', 'm8']
    renderApp({ path: `${base}/b3`, client: held.client })
    await user.click(await screen.findByRole('button', { name: 'Bajar semana 1' }))
    expect(screen.getByRole('button', { name: 'Guardar orden' })).toBeDisabled()
    await user.click(screen.getByRole('checkbox')); await user.click(screen.getByRole('button', { name: 'Guardar orden' }))
    expect(screen.getByRole('button', { name: 'Guardar orden' })).toBeDisabled()
    held.release(); await waitFor(() => expect(screen.queryByRole('button', { name: 'Guardar orden' })).not.toBeInTheDocument())
    expect(state.weeks.find((w) => w.id === 'w1')?.weekNumber).toBe(2)
    await user.click(screen.getByRole('button', { name: 'Retirar semana 2' }))
    const dialog = screen.getByRole('dialog')
    expect(dialog).toHaveTextContent('2 marcas de lectura de miembros distintos'); expect(dialog).toHaveTextContent('30 días')
    expect(within(dialog).getByRole('button', { name: 'Cancelar' })).toHaveFocus()
    await user.click(within(dialog).getByRole('button', { name: 'Cancelar' }))
    expect(state.weeks.find((w) => w.id === 'w1')).not.toHaveProperty('deletedAt')
    await user.click(screen.getByRole('button', { name: 'Retirar semana 2' })); await user.click(screen.getByRole('button', { name: 'Confirmar retirada' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(state.weeks.find((w) => w.id === 'w1')).toHaveProperty('deletedAt', state.now)
    expect(state.completions.w1).toEqual(['m1', 'm8', 'm8'])
    expect(screen.getByRole('button', { name: 'Añadir semana' })).toHaveFocus()
  })
  it('retains a removed association in the calendar date-only editor until deliberate unlink', async () => {
    const state = createClubState(), api = createMockClient({ state }), user = userEvent.setup()
    await api.removeReadingWeek('b3', 'w1')
    renderApp({ path: '/administracion/reuniones/mt1/editar', client: api })
    const select = await screen.findByLabelText('Semana de lectura')
    expect(select).toHaveValue('w1'); expect(within(select).getByRole('option', { name: /Semana retirada/ })).toBeDisabled()
    change('Fecha', '2026-12-02'); await user.click(screen.getByRole('button', { name: 'Guardar reunión' }))
    await waitFor(() => expect(state.meetings.find((m) => m.id === 'mt1')?.startsAt).toContain('2026-12-02'))
    expect(state.weeks[0].meetingId).toBe('mt1')
    await user.selectOptions(await screen.findByLabelText('Semana de lectura'), '')
    await user.click(screen.getByRole('button', { name: 'Guardar reunión' }))
    await waitFor(() => expect(state.weeks[0].meetingId).toBeNull())
  })
})
