import { fireEvent, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { describe, expect, it } from 'vitest'
import { createClubState, createEmptyState } from '../api/mock/fixtures'
import { createMockClient } from '../api/mock/mockClient'
import { holdCalls, trackCalls } from '../test/clients'
import { renderApp } from '../test/renderApp'

const base = '/administracion/reuniones'
const change = (name: string, value: string) => fireEvent.change(screen.getByLabelText(name), { target: { value } })
describe('admin meeting calendar', () => {
  it('links the hub to both groups and all meeting editors', async () => {
    const user = userEvent.setup()
    renderApp({ path: '/administracion' })
    await screen.findByRole('heading', { name: 'Administración' })
    await user.click(within(screen.getByRole('main')).getByRole('link', { name: 'Reuniones', exact: true }))
    expect(await screen.findByRole('heading', { name: 'Próximas reuniones' })).toBeInTheDocument()
    expect(screen.getAllByRole('link', { name: /^Editar reunión del/ })).toHaveLength(8)
    expect(screen.getByText('Cancelada')).toBeInTheDocument()
    expect(screen.getByText('Sin libro')).toBeInTheDocument()
  })
  it('shows loading, retry, empty and unknown meeting states', async () => {
    const user = userEvent.setup()
    const held = holdCalls(createMockClient({ state: createEmptyState(), failures: { listAdminMeetings: 1 } }), 'listAdminMeetings')
    const tracked = trackCalls(held.client)
    const app = renderApp({ path: base, client: tracked.client })
    await waitFor(() => expect(tracked.calls).toContain('listAdminMeetings'))
    expect(screen.getByText('Cargando…')).toBeInTheDocument()
    held.release()
    expect(await screen.findByText('No se han podido cargar las reuniones.')).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Reintentar' }))
    expect(await screen.findByText(/No hay próximas reuniones/)).toBeInTheDocument()
    app.unmount()
    renderApp({ path: `${base}/unknown/editar` })
    expect(await screen.findByRole('heading', { name: 'No encontramos esta reunión' })).toBeInTheDocument()
  })
  it.each(['member', 'curator'] as const)('denies direct routes to %s without admin reads', async (session) => {
    for (const path of [base, `${base}/nueva`, `${base}/mt1/editar`]) {
      const tracked = trackCalls(createMockClient({ session }))
      const app = renderApp({ path, client: tracked.client })
      expect(await screen.findByRole('heading', { name: 'Sección reservada' })).toBeInTheDocument()
      expect(tracked.clubDataCalls()).toEqual([])
      app.unmount()
    }
  })
  it('creates in club timezone, refuses missing/DST input locally and preserves values after failed save', async () => {
    const user = userEvent.setup(), state = createClubState()
    const tracked = trackCalls(createMockClient({ state, failures: { createMeeting: 1 } }))
    renderApp({ path: `${base}/nueva`, client: tracked.client })
    const date = await screen.findByLabelText('Fecha')
    expect(date).toHaveFocus()
    expect(screen.getByText(/Europe\/Madrid/)).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Guardar reunión' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('válidas')
    change('Fecha', '2026-03-29'); change('Hora', '02:30')
    await user.click(screen.getByRole('button', { name: 'Guardar reunión' }))
    expect(screen.getByRole('alert')).toHaveTextContent('no existe')
    change('Fecha', '2026-10-25')
    await user.click(screen.getByRole('button', { name: 'Guardar reunión' }))
    expect(screen.getByRole('alert')).toHaveTextContent('ambigua')
    expect(tracked.calls).not.toContain('createMeeting')
    change('Fecha', '2026-01-15'); change('Hora', '19:30')
    await user.click(screen.getByRole('button', { name: 'Guardar reunión' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('Error simulado')
    expect(date).toHaveValue('2026-01-15')
    expect(state.meetings).toHaveLength(8)
    await user.click(screen.getByRole('button', { name: 'Guardar reunión' }))
    expect(await screen.findByRole('heading', { name: 'Editar reunión' })).toBeInTheDocument()
    expect(state.meetings.at(-1)?.startsAt).toBe('2026-01-15T18:30:00.000Z')
    expect(screen.getByLabelText('Fecha')).toHaveValue('2026-01-15')
    expect(screen.getByLabelText('Hora')).toHaveValue('19:30')
  })
  it('retains a conflicting link on failure and clears week selection when the book changes', async () => {
    const user = userEvent.setup(), state = createClubState()
    renderApp({ path: `${base}/mt1/editar`, client: createMockClient({ state }) })
    await screen.findByLabelText('Fecha')
    const original = structuredClone(state)
    const occupied = state.weeks.find((w) => w.meetingId === 'mt2')!
    change('Semana de lectura', occupied.id)
    await user.click(screen.getByRole('button', { name: 'Guardar reunión' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('otra reunión')
    expect(screen.getByLabelText('Semana de lectura')).toHaveValue(occupied.id)
    expect(state).toEqual(original)
    change('Libro', '')
    expect(screen.getByLabelText('Semana de lectura')).toHaveValue('')
    expect(screen.getByLabelText('Semana de lectura')).toBeDisabled()
  })
  it('cancels with accessible confirmation, restores and preserves revoked attendance on correction', async () => {
    const user = userEvent.setup(), state = createClubState(), api = createMockClient({ state })
    await api.revokeMember('m2')
    const before = structuredClone(state.meetings.find((m) => m.id === 'mt1'))
    renderApp({ path: `${base}/mt1/editar`, client: api })
    await screen.findByLabelText('Fecha')
    expect(screen.getByText('Historial de miembros sin acceso (solo lectura)')).toBeInTheDocument()
    expect(screen.queryByRole('checkbox', { name: 'Mateo' })).not.toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Cancelar reunión' }))
    const dialog = screen.getByRole('dialog')
    expect(within(dialog).getByRole('button', { name: 'Cancelar', exact: true })).toHaveFocus()
    await user.keyboard('{Escape}')
    expect(screen.getByRole('button', { name: 'Cancelar reunión' })).toHaveFocus()
    expect(state.meetings.find((m) => m.id === 'mt1')).toEqual(before)
    await user.click(screen.getByRole('button', { name: 'Cancelar reunión' }))
    await user.click(screen.getByRole('button', { name: 'Confirmar cancelación' }))
    expect(await screen.findByRole('button', { name: 'Restaurar reunión' })).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Guardar asistencia' })).not.toBeInTheDocument()
    expect(screen.getByText(/No se puede editar la asistencia/)).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Restaurar reunión' }))
    await screen.findByRole('button', { name: 'Guardar asistencia' })
    expect(state.meetings.find((m) => m.id === 'mt1')).toEqual(before)
    for (const checkbox of screen.getAllByRole('checkbox')) if ((checkbox as HTMLInputElement).checked) await user.click(checkbox)
    await user.click(screen.getByRole('button', { name: 'Guardar asistencia' }))
    await waitFor(() => expect(state.meetings.find((m) => m.id === 'mt1')?.attendance).toEqual(['m2']))
    expect(await screen.findByText('1 asistentes registrados')).toBeInTheDocument()
  })
  it('keeps entered attendance after failure and disables duplicate submissions in flight', async () => {
    const user = userEvent.setup(), state = createClubState()
    const held = holdCalls(createMockClient({ state, failures: { setMeetingAttendance: 1 } }), 'setMeetingAttendance')
    const tracked = trackCalls(held.client)
    renderApp({ path: `${base}/mt1/editar`, client: tracked.client })
    await screen.findByLabelText('Fecha')
    await user.click(screen.getByRole('checkbox', { name: 'Mateo' }))
    const save = screen.getByRole('button', { name: 'Guardar asistencia' })
    await user.click(save)
    expect(save).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Guardar reunión' })).toBeDisabled()
    await user.click(save)
    expect(tracked.calls.filter((call) => call === 'setMeetingAttendance')).toHaveLength(1)
    held.release()
    expect(await screen.findByRole('alert')).toHaveTextContent('Error simulado')
    expect(screen.getByRole('checkbox', { name: 'Mateo' })).not.toBeChecked()
  })
  it('offers no attendance editor for future meetings and shows the server reason', async () => {
    renderApp({ path: `${base}/mt3/editar` })
    expect(await screen.findByText(/La asistencia se puede registrar después/)).toBeInTheDocument()
    expect(screen.queryByRole('checkbox')).not.toBeInTheDocument()
  })
})
